// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT2bWkZFEElh6BURRzwEZMnOL3H9K29q8',
    appId: '1:567870683727:web:0d9733d239f5815989483a',
    messagingSenderId: '567870683727',
    projectId: 'hotelio-9465b',
    authDomain: 'hotelio-9465b.firebaseapp.com',
    storageBucket: 'hotelio-9465b.appspot.com',
    measurementId: 'G-9Y679T51RR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrzy5_rGLKE8h-e1UjtTxo-K9IYco3L6o',
    appId: '1:567870683727:android:9dc26e5d355c7fae89483a',
    messagingSenderId: '567870683727',
    projectId: 'hotelio-9465b',
    storageBucket: 'hotelio-9465b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU2pz4-9HvyjrUeLRie1MBMhHkg57l8wY',
    appId: '1:567870683727:ios:9fc9ad696870868489483a',
    messagingSenderId: '567870683727',
    projectId: 'hotelio-9465b',
    storageBucket: 'hotelio-9465b.appspot.com',
    iosClientId: '567870683727-jp1hr2gnekgq8n6r11mvnce7ok3trv16.apps.googleusercontent.com',
    iosBundleId: 'com.example.hotelio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU2pz4-9HvyjrUeLRie1MBMhHkg57l8wY',
    appId: '1:567870683727:ios:9a7eebcf1bbaeb8689483a',
    messagingSenderId: '567870683727',
    projectId: 'hotelio-9465b',
    storageBucket: 'hotelio-9465b.appspot.com',
    iosClientId: '567870683727-k3bbs8m8oikgf760qa4bp36afnvi0dao.apps.googleusercontent.com',
    iosBundleId: 'com.example.hotelio.RunnerTests',
  );
}
